var dataOfCompanies = [
"Tsmc@台灣積體電路製造@www.tsmc.com.tw@http://www.glassdoor.com/Salary/Tsmc-Salaries-E4130.htm",
"HTC@宏達國際電子@www.htc.com@http://www.glassdoor.com/Salary/HTC-Salaries-E41150.htm",
"National Taiwan University@國立臺灣大學@www.ntu.edu.tw@http://www.glassdoor.com/Salary/National-Taiwan-University-Salaries-E254537.htm",
"Academia Sinica@中央研究院@www.sinica.edu.tw@http://www.glassdoor.com/Salary/Academia-Sinica-Salaries-E343333.htm",
"IBM@台灣國際商業機器@www.ibm.com.tw@http://www.glassdoor.com/Salary/IBM-Salaries-E354.htm",
"ASUS@華碩電腦@www.asus.com.tw@http://www.glassdoor.com/Salary/ASUS-Salaries-E40093.htm",
"Trend Micro@趨勢科技@www.trendmicro.com@http://www.glassdoor.com/Salary/Trend-Micro-Salaries-E8983.htm",
"Deloitte@勤業眾信@www.deloitte.com@http://www.glassdoor.com/Salary/Deloitte-Salaries-E2763.htm",
"MediaTek@聯發科技@www.mediatek.com@http://www.glassdoor.com/Salary/MediaTek-Salaries-E40142.htm",
"Hewlett-Packard@惠普@www.hp.com@http://www.glassdoor.com/Salary/Hewlett-Packard-Salaries-E327.htm",
"ITRI@財團法人工業技術研究院@www.itri.org.tw@http://www.glassdoor.com/Salary/ITRI-Salaries-E388187.htm",
"PwC@資誠聯合會計師事務所@www.pwc.com@http://www.glassdoor.com/Salary/PwC-Salaries-E8450.htm",
"Quanta Computer@廣達電腦@www.quantatw.com@http://www.glassdoor.com/Salary/Quanta-Computer-Salaries-E11939.htm",
"Yahoo@雅虎資訊@www.yahoo.com@http://www.glassdoor.com/Salary/Yahoo-Salaries-E5807.htm",
"Wistron@緯創資通@www.wistron.com@http://www.glassdoor.com/Salary/Wistron-Salaries-E15218.htm",
"MStar Semiconductor@晨星半導體@www.mstarsemi.com@http://www.glassdoor.com/Salary/MStar-Semiconductor-Salaries-E134936.htm",
"Synopsys@新思科技@www.synopsys.com@http://www.glassdoor.com/Salary/Synopsys-Salaries-E2143.htm",
"Compal Electronics@仁寶電腦@www.compal.com@http://www.glassdoor.com/Salary/Compal-Electronics-Salaries-E13464.htm",
"KPMG@安侯建業聯合會計師事務所@www.kpmg.com@http://www.glassdoor.com/Salary/KPMG-Salaries-E2867.htm",
"Hess Educational@何嘉仁文教事業@hess.com.tw@http://www.glassdoor.com/Salary/Hess-Educational-Salaries-E379093.htm",
"National Chiao Tung University@國立交通大學@www.nctu.edu.tw@http://www.glassdoor.com/Salary/National-Chiao-Tung-University-Salaries-E329412.htm",
"Microsoft@微軟@www.microsoft.com@http://www.glassdoor.com/Salary/Microsoft-Salaries-E1651.htm",
"Moxa Inc.@四零四科技@www.moxa.com@http://www.glassdoor.com/Salary/Moxa-Inc-Salaries-E117549.htm",
"Pegatron@和碩集團@www.pegatroncorp.com@http://www.glassdoor.com/Salary/Pegatron-Salaries-E337948.htm",
"SpringSoft@SpringSoft@www.springsoft.com@http://www.glassdoor.com/Salary/SpringSoft-Salaries-E117526.htm",
"Delta Electronics@台達電子@www.delta.com.tw@http://www.glassdoor.com/Salary/Delta-Electronics-Salaries-E41146.htm",
"Institute For Information Industry@財團法人資訊工業策進會@www.iii.org@http://www.glassdoor.com/Salary/Institute-For-Information-Industry-Salaries-E234871.htm",
"CTCI@中鼎工程@www.ctci.com.tw@http://www.glassdoor.com/Salary/CTCI-Salaries-E138031.htm",
"Chunghwa Telecom@中華電信@www.cht.com.tw@http://www.glassdoor.com/Salary/Chunghwa-Telecom-Salaries-E6565.htm",
"Digital River@亞太數位潮流科技@www.digitalriver.com@http://www.glassdoor.com/Salary/Digital-River-Salaries-E8393.htm",
"Foxconn@鴻海精密工業@www.fih-foxconn.com@http://www.glassdoor.com/Salary/Foxconn-Salaries-E42401.htm",
"Chi Mei Optoelectronics@奇美電子@www.chimei-innolux.com@http://www.glassdoor.com/Salary/Chi-Mei-Optoelectronics-Salaries-E35042.htm",
"National Tsing Hua University@國立清華大學@www.nthu.edu.tw@http://www.glassdoor.com/Salary/National-Tsing-Hua-University-Salaries-E240834.htm",
"NTUH@國立臺灣大學醫學院附設醫院竹東分院@www.ntuh.gov.tw@http://www.glassdoor.com/Salary/NTUH-Salaries-E424897.htm",
"Google@谷歌@www.google.com@http://www.glassdoor.com/Salary/Google-Salaries-E9079.htm",
"AMD@美商超微半導體@www.amd.com@http://www.glassdoor.com/Salary/AMD-Salaries-E15.htm",
"The Nielsen Company@尼爾森行銷研究顧問@www.nielsen.com@http://www.glassdoor.com/Salary/The-Nielsen-Company-Salaries-E3776.htm",
"Texas Instruments@德州儀器工業@www.ti.com@http://www.glassdoor.com/Salary/Texas-Instruments-Salaries-E651.htm",
"Broadcom@美商博通國際研發服務@www.broadcom.com@http://www.glassdoor.com/Salary/Broadcom-Salaries-E6926.htm",
"Garmin@Garmin@www.garmin.com@http://www.glassdoor.com/Salary/Garmin-Salaries-E12667.htm",
"Advantech@研華@www.advantech.com@http://www.glassdoor.com/Salary/Advantech-Salaries-E152696.htm",
"ZyXEL Communications@合勤科技@www.zyxel.com@http://www.glassdoor.com/Salary/ZyXEL-Communications-Salaries-E34904.htm",
"CyberLink@訊連科技@www.cyberlink.com@http://www.glassdoor.com/Salary/CyberLink-Salaries-E43347.htm",
"Inventec@英業達@www.inventec.com@http://www.glassdoor.com/Salary/Inventec-Salaries-E13485.htm",
"EY@安永聯合會計師事務所@www.ey.com@http://www.glassdoor.com/Salary/EY-Salaries-E2784.htm",
"Starbucks@統一星巴克@starbucks.com@http://www.glassdoor.com/Salary/Starbucks-Salaries-E2202.htm",
"Motorola Mobility@通用先進系統@www.motorola.com@http://www.glassdoor.com/Salary/Motorola-Mobility-Salaries-E451.htm",
"Siemens@西門子@www.siemens.com@http://www.glassdoor.com/Salary/Siemens-Salaries-E3510.htm",
"Applied Materials@台灣應用材料@www.appliedmaterials.com@http://www.glassdoor.com/Salary/Applied-Materials-Salaries-E1139.htm",
"3M@明尼蘇達礦業製造@www.mmm.com@http://www.glassdoor.com/Salary/3M-Salaries-E446.htm",
"Ogilvy &amp; Mather@奧美公共關係顧問@www.ogilvy.com@http://www.glassdoor.com/Salary/Ogilvy-and-Mather-Salaries-E13661.htm",
"D-Link@D-Link_友訊科技@www.dlink.com@http://www.glassdoor.com/Salary/D-Link-Salaries-E4041.htm",
"Corel@科立爾數位科技@www.corel.com@http://www.glassdoor.com/Salary/Corel-Salaries-E3764.htm",
"Advanced Digital Broadcast@遠昇科技@www.adbglobal.com@http://www.glassdoor.com/Salary/Advanced-Digital-Broadcast-Salaries-E195268.htm",
"AU Optronics@友達光電@www.auo.com@http://www.glassdoor.com/Salary/AU-Optronics-Salaries-E16126.htm",
"Acer (Taiwan HQ)@宏碁@www.acer-group.com@http://www.glassdoor.com/Salary/Acer-Taiwan-HQ-Salaries-E3802.htm",
"Accton Technology@智邦科技@www.accton.com@http://www.glassdoor.com/Salary/Accton-Technology-Salaries-E12704.htm",
"Effective International English@美好國際企業管理顧問@www.eie.com.tw@http://www.glassdoor.com/Reviews/Effective-International-English-Reviews-E400379.htm",
"Inventec Appliance Corp.@英華達@www.iac.com.tw@http://www.glassdoor.com/Salary/Inventec-Appliance-Corp-Salaries-E156677.htm",
"Intel Corporation@英特爾@www.intel.com@http://www.glassdoor.com/Salary/Intel-Corporation-Salaries-E1519.htm",
"SAP@思愛普軟體系統@www.sap.com@http://www.glassdoor.com/Salary/SAP-Salaries-E10471.htm",
"Ericsson-Worldwide@愛立信@www.ericsson.com@http://www.glassdoor.com/Salary/Ericsson-Worldwide-Salaries-E3472.htm",
"Morgan Stanley@摩根士史利美@www.morganstanley.com@http://www.glassdoor.com/Salary/Morgan-Stanley-Salaries-E2282.htm",
"Qualcomm@高通@www.qualcomm.com@http://www.glassdoor.com/Salary/Qualcomm-Salaries-E640.htm",
"Alcatel-Lucent@國際標準電子@www.alcatel-lucent.com@http://www.glassdoor.com/Salary/Alcatel-Lucent-Salaries-E3453.htm",
"McKinsey & Company@麥肯@www.mckinsey.com@http://www.glassdoor.com/Salary/McKinsey-and-Company-Salaries-E2893.htm",
"NVIDIA@輝達@www.nvidia.com@http://www.glassdoor.com/Salary/NVIDIA-Salaries-E7633.htm",
"Eastman Chemical@美商首諾@www.eastman.com@http://www.glassdoor.com/Salary/Eastman-Chemical-Salaries-E2452.htm",
"Groupon@渥奇數位資訊@www.groupon.com@http://www.glassdoor.com/Salary/Groupon-Salaries-E301291.htm",
"Corning@寧顯示玻璃@www.corning.com@http://www.glassdoor.com/Salary/Corning-Salaries-E183.htm",
"Lam Research@科林研發@www.lamresearch.com@http://www.glassdoor.com/Salary/Lam-Research-Salaries-E1582.htm",
"NXP@恩智浦半導體@www.nxp.com@http://www.glassdoor.com/Salary/NXP-Salaries-E13528.htm",
"ASML@艾司摩爾@www.asml.com@http://www.glassdoor.com/Salary/ASML-Salaries-E5781.htm",
"Kantar Worldpanel@@www.kantarworldpanel.com@http://www.glassdoor.com/Salary/Kantar-Worldpanel-Salaries-E425946.htm",
"BenQ@@www.benq.com@http://www.glassdoor.com/Salary/BenQ-Salaries-E14509.htm",
"Cabot Microelectronics@@www.cabotcmp.com@http://www.glassdoor.com/Salary/Cabot-Microelectronics-Salaries-E11440.htm",
"Chinatrust Commercial Bank@@www.chinatrustusa.com@http://www.glassdoor.com/Salary/Chinatrust-Commercial-Bank-Salaries-E433805.htm",
"Advanced Semiconductor Engineering@@www.aseglobal.com@http://www.glassdoor.com/Salary/Advanced-Semiconductor-Engineering-Salaries-E4126.htm",
"Compal Communication@@www.compalcomm.com@http://www.glassdoor.com/Salary/Compal-Communication-Salaries-E343314.htm",
"RealTek Semiconductor Corp@@www.realtek.com.tw@http://www.glassdoor.com/Salary/RealTek-Semiconductor-Corp-Salaries-E110961.htm",
"Taiwan Army@@www.mnd.gov.tw@http://www.glassdoor.com/Reviews/Taiwan-Army-Reviews-E214974.htm",
"Gloria English School@@www.glo.com.tw@http://www.glassdoor.com/Salary/Gloria-English-School-Salaries-E295935.htm",
"Macronix International@@www.macronix.com@http://www.glassdoor.com/Salary/Macronix-International-Salaries-E6072.htm",
"Gemtek@@www.gemtek.com.tw@http://www.glassdoor.com/Salary/Gemtek-Salaries-E345406.htm",
"Kojen@@www.kojenenglish.com@http://www.glassdoor.com/Salary/Kojen-Salaries-E391769.htm",
"HAITEC@@www.haitec.com.tw@http://www.glassdoor.com/Salary/HAITEC-Salaries-E536457.htm",
"Nan Shan Life Insurance@@www.nanshanlife.com.tw@http://www.glassdoor.com/Salary/Nan-Shan-Life-Insurance-Salaries-E475858.htm",
"National Cheng Kung University@@www.ncku.edu.tw@http://www.glassdoor.com/Salary/National-Cheng-Kung-University-Salaries-E675266.htm",
"ACTi Corporation@@www.acti.com@http://www.glassdoor.com/Salary/ACTi-Corporation-Salaries-E646639.htm",
"Himax@@www.himax.com.tw@http://www.glassdoor.com/Salary/Himax-Salaries-E40806.htm",
"QNAP@@www.qnap.com@http://www.glassdoor.com/Salary/QNAP-Salaries-E340193.htm",
"Accenture@@www.accenture.com@http://www.glassdoor.com/Salary/Accenture-Salaries-E4138.htm",
"Bank of America@@www.bankofamerica.com@http://www.glassdoor.com/Salary/Bank-of-America-Salaries-E8874.htm",
"J.P. Morgan@@www.jpmorgan.com@http://www.glassdoor.com/Salary/J-P-Morgan-Salaries-E145.htm",
"Dell@@www.dell.com@http://www.glassdoor.com/Salary/Dell-Salaries-E1327.htm",
"McDonald's@@www.mcdonalds.com@http://www.glassdoor.com/Salary/McDonald-s-Salaries-E432.htm",
"Citi@@www.citigroup.com@http://www.glassdoor.com/Salary/Citi-Salaries-E8843.htm",
"Procter &amp; Gamble@@www.pg.com@http://www.glassdoor.com/Salary/Procter-and-Gamble-Salaries-E544.htm",
"Symantec@@www.symantec.com@http://www.glassdoor.com/Salary/Symantec-Salaries-E1931.htm",
"UBS@@www.ubs.com@http://www.glassdoor.com/Salary/UBS-Salaries-E3419.htm",
"HSBC Holdings@@www.hsbc.com@http://www.glassdoor.com/Salary/HSBC-Holdings-Salaries-E3482.htm",
"NIKE@@www.nikeinc.com@http://www.glassdoor.com/Salary/NIKE-Salaries-E1699.htm",
"National Instruments@@www.ni.com@http://www.glassdoor.com/Salary/National-Instruments-Salaries-E4030.htm",
"Boston Consulting Group@@www.bcg.com@http://www.glassdoor.com/Salary/Boston-Consulting-Group-Salaries-E3879.htm",
"Dow Chemical@@www.dow.com@http://www.glassdoor.com/Salary/Dow-Chemical-Salaries-E207.htm",
"Standard Chartered Bank@@www.standardchartered.com.hk@http://www.glassdoor.com/Salary/Standard-Chartered-Bank-Salaries-E226853.htm",
"KLA-Tencor@@www.kla-tencor.com@http://www.glassdoor.com/Salary/KLA-Tencor-Salaries-E1557.htm",
"Cadence Design Systems@@www.cadence.com@http://www.glassdoor.com/Salary/Cadence-Design-Systems-Salaries-E1217.htm",
"Atos@@www.atos.net@http://www.glassdoor.com/Salary/Atos-Salaries-E10686.htm",
"Compuware@@www.compuware.com@http://www.glassdoor.com/Salary/Compuware-Salaries-E35473.htm",
"Adecco@@www.adecco.com@http://www.glassdoor.com/Salary/Adecco-Salaries-E1089.htm",
"Logitech@@www.logitech.com@http://www.glassdoor.com/Salary/Logitech-Salaries-E3806.htm",
"Amway@@www.amway.com@http://www.glassdoor.com/Salary/Amway-Salaries-E13321.htm",
"Fitch Ratings@@www.fitchratings.com@http://www.glassdoor.com/Salary/Fitch-Ratings-Salaries-E8579.htm",
"Saatchi &amp; Saatchi@@www.saatchi.com@http://www.glassdoor.com/Salary/Saatchi-and-Saatchi-Salaries-E3506.htm",
"DBS Group Holdings@@www.dbs.com@http://www.glassdoor.com/Salary/DBS-Group-Holdings-Salaries-E9444.htm",
"Rhythm &amp; Hues Studios@@www.rhythm.com@http://www.glassdoor.com/Salary/Rhythm-and-Hues-Studios-Salaries-E9712.htm",
"Standard Chartered@@www.standardchartered.com@http://www.glassdoor.com/Salary/Standard-Chartered-Salaries-E10238.htm",
"DBS Bank@@dbs.com.sg@http://www.glassdoor.com/Salary/DBS-Bank-Salaries-E611812.htm",
"Michelin@@www.michelin.com@http://www.glassdoor.com/Salary/Michelin-Salaries-E3294.htm",
"American Megatrends@@www.ami.com@http://www.glassdoor.com/Salary/American-Megatrends-Salaries-E3066.htm",
"Fuji Xerox@@www.fujixerox.co.jp@http://www.glassdoor.com/Salary/Fuji-Xerox-Salaries-E14135.htm",
"CLSA@@www.clsa.com@http://www.glassdoor.com/Salary/CLSA-Salaries-E298772.htm",
"Transcend Information@@www.transcend-info.com@http://www.glassdoor.com/Salary/Transcend-Information-Salaries-E416579.htm",
"A10 Networks@@www.a10networks.com@http://www.glassdoor.com/Salary/A10-Networks-Salaries-E261028.htm",
"United Microelectronics@@www.umc.com@http://www.glassdoor.com/Salary/United-Microelectronics-Salaries-E7721.htm",
"Novatek@@www.novatek.com@http://www.glassdoor.com/Salary/Novatek-Salaries-E383265.htm",
"Promise Technology@@www.promise.com@http://www.glassdoor.com/Salary/Promise-Technology-Salaries-E8602.htm",
"VIA Technologies@@www.viatech.com@http://www.glassdoor.com/Salary/VIA-Technologies-Salaries-E9470.htm",
"ABeam Consulting@@www.abeam.com@http://www.glassdoor.com/Salary/ABeam-Consulting-Salaries-E228354.htm",
"Acer@@www.acer.fr@http://www.glassdoor.com/Salary/Acer-Salaries-E504922.htm",
"Nuvoton@@www.nuvoton.com@http://www.glassdoor.com/Salary/Nuvoton-Salaries-E381599.htm",
"NHRI@@www.nhri.org.tw@http://www.glassdoor.com/Salary/NHRI-Salaries-E390002.htm",
"China Airlines@@www.china-airlines.com@http://www.glassdoor.com/Salary/China-Airlines-Salaries-E7532.htm",
"Yuanta Securities@@www.yuanta.com.tw@http://www.glassdoor.com/Salary/Yuanta-Securities-Salaries-E228478.htm",
"ChipMOS@@www.chipmos.com.tw@http://www.glassdoor.com/Reviews/ChipMOS-Reviews-E15111.htm",
"Yulon Motor@@www.yulon-motor.com.tw@http://www.glassdoor.com/Salary/Yulon-Motor-Salaries-E8298.htm",
"Leadtek@@www.leadtek.com@http://www.glassdoor.com/Reviews/Leadtek-Reviews-E28894.htm",
"GBT (Gigabyte Technology)@@www.gigabyte.us@http://www.glassdoor.com/Salary/GBT-Gigabyte-Technology-Salaries-E287318.htm",
"BenQ IT Co. Ltd.@@www.benq.com.tw@http://www.glassdoor.com/Salary/BenQ-IT-Co-Ltd-Salaries-E41103.htm",
"Wintek@@www.wintek.com.tw@http://www.glassdoor.com/Salary/Wintek-Salaries-E41121.htm",
"China Post Online@@www.chinapost.com.cn@http://www.glassdoor.com/Reviews/China-Post-Online-Reviews-E352845.htm",
"SinoPac@@www.sinopac.com@http://www.glassdoor.com/Salary/SinoPac-Salaries-E7125.htm",
"AUO@@www.auo.com@http://www.glassdoor.com/Salary/AUO-Salaries-E472523.htm",
"Hon Hai@@www.foxconn.com@http://www.glassdoor.com/Salary/Hon-Hai-Salaries-E8933.htm",
"ProMOS Technologies@@www.promos.com.tw@http://www.glassdoor.com/Salary/ProMOS-Technologies-Salaries-E41158.htm",
"Ubee Interactive@@www.ubeeinteractive.com@http://www.glassdoor.com/Salary/Ubee-Interactive-Salaries-E361234.htm",
"ERA Communications@@ERA.com.tw@http://www.glassdoor.com/Reviews/ERA-Communications-Reviews-E426002.htm",
"Ministry of National Defense China@@eng.mod.gov.cn@http://www.glassdoor.com/Salary/Ministry-of-National-Defense-China-Salaries-E459571.htm",
"Fast Technologies@@www.fast.com.tw@http://www.glassdoor.com/Salary/Fast-Technologies-Salaries-E566794.htm",
"Siliconware Precision Industries@@www.spil.com.tw@http://www.glassdoor.com/Reviews/Siliconware-Precision-Industries-Reviews-E11356.htm",
"Yang Ming@@www.yml.com.tw@http://www.glassdoor.com/Salary/Yang-Ming-Salaries-E26306.htm",
"Novatek Microelectronics@@www.novatek.com.tw@http://www.glassdoor.com/Reviews/Novatek-Microelectronics-Reviews-E390618.htm",
"Powerchip Semiconductor@@www.psc.com.tw@http://www.glassdoor.com/Salary/Powerchip-Semiconductor-Salaries-E41145.htm",
"DIGITIMES@@www.digitimes.com@http://www.glassdoor.com/Reviews/DIGITIMES-Reviews-E675768.htm",
"Taiwan Instrument@@www.ticgroup.com.tw@http://www.glassdoor.com/Salary/Taiwan-Instrument-Salaries-E685595.htm",
"INNOLUX@@www.innolux.com@http://www.glassdoor.com/Salary/INNOLUX-Salaries-E229767.htm",
"LiteOn IT@@www.liteonit.com@http://www.glassdoor.com/Salary/LiteOn-IT-Salaries-E233522.htm",
"Shuttle Computer Group@@www.us.shuttle.com@http://www.glassdoor.com/Salary/Shuttle-Computer-Group-Salaries-E261139.htm",
"ACTis bvba@@www.actis.be@http://www.glassdoor.com/Salary/ACTis-bvba-Salaries-E351677.htm",
"Citibank Taiwan@@www.citibank.com.tw@http://www.glassdoor.com/Salary/Citibank-Taiwan-Salaries-E574773.htm",
"Taiwan Life Insurance Company@@www.twlife.com.tw@http://www.glassdoor.com/Salary/Taiwan-Life-Insurance-Company-Salaries-E672227.htm",
"Evergreen Marine@@www.evergreen-marine.com@http://www.glassdoor.com/Salary/Evergreen-Marine-Salaries-E3595.htm",
"National Chenchi University@@www.nccu.edu.tw@http://www.glassdoor.com/Salary/National-Chenchi-University-Salaries-E321124.htm",
"PTSGI@@www.ptsgi.com@http://www.glassdoor.com/Reviews/PTSGI-Reviews-E350459.htm",
"Eurocentre@@www.eurocentre.org@http://www.glassdoor.com/Reviews/Eurocentre-Reviews-E366823.htm",
"Global Unichip Corporation@@www.globalunichip.com@http://www.glassdoor.com/Salary/Global-Unichip-Corporation-Salaries-E483572.htm",
"Chang Gung Memorial Hospital@@www.cgmh.org.tw@http://www.glassdoor.com/Salary/Chang-Gung-Memorial-Hospital-Salaries-E568884.htm",
"China Steel Machinery Corporation@@www.csmc.com.tw@http://www.glassdoor.com/Reviews/China-Steel-Machinery-Corporation-Reviews-E606066.htm",
"China Times@@news.chinatimes.com@http://www.glassdoor.com/Salary/China-Times-Salaries-E630324.htm",
"Vanguard International Semiconductor@@www.vis.com.tw@http://www.glassdoor.com/Salary/Vanguard-International-Semiconductor-Salaries-E695144.htm",
"Orient Semiconductor@@www.ose.com.tw@http://www.glassdoor.com/Salary/Orient-Semiconductor-Salaries-E9292.htm",
"Digimax, Inc.@@www.digimax.com.tw@http://www.glassdoor.com/Reviews/Digimax-Inc-Reviews-E116691.htm",
"Cosmos Bank@@www.cosmos.com.tw@http://www.glassdoor.com/Reviews/Cosmos-Bank-Reviews-E200574.htm",
"Continental Engineering@@www.cec.com.tw@http://www.glassdoor.com/Salary/Continental-Engineering-Salaries-E514165.htm",
"Ubitus@@www.ubitus.net@http://www.glassdoor.com/Salary/Ubitus-Salaries-E572294.htm",
"Yangluck International Manpower@@www.yangluck.com.tw@http://www.glassdoor.com/Reviews/Yangluck-International-Manpower-Reviews-E575691.htm",
"International Games System@@www.igs.com.tw@http://www.glassdoor.com/Salary/International-Games-System-Salaries-E576917.htm",
"Moldex3D@@www.moldex3d.com@http://www.glassdoor.com/Reviews/Moldex3D-Reviews-E609882.htm",
"Phison@@www.phison.com@http://www.glassdoor.com/Salary/Phison-Salaries-E690997.htm",
"Oracle@@www.oracle.com@http://www.glassdoor.com/Salary/Oracle-Salaries-E1737.htm",
"Apple@@www.apple.com@http://www.glassdoor.com/Salary/Apple-Salaries-E1138.htm",
"Verizon@@www.verizon.com@http://www.glassdoor.com/Salary/Verizon-Salaries-E89.htm",
"GE@@www.ge.com@http://www.glassdoor.com/Salary/GE-Salaries-E277.htm",
"Tech Mahindra Limited@@www.techmahindra.com@http://www.glassdoor.com/Salary/Tech-Mahindra-Limited-Salaries-E135932.htm",
"Johnson &amp; Johnson@@www.jnj.com@http://www.glassdoor.com/Salary/Johnson-and-Johnson-Salaries-E364.htm",
"Sun Microsystems@@www.sun.com@http://www.glassdoor.com/Salary/Sun-Microsystems-Salaries-E1924.htm",
"Bloomberg L.P.@@www.bloomberg.com@http://www.glassdoor.com/Salary/Bloomberg-L-P-Salaries-E3096.htm",
"Citibank@@www.citibank.com@http://www.glassdoor.com/Salary/Citibank-Salaries-E13604.htm",
"Barnes &amp; Noble@@www.barnesandnobleinc.com@http://www.glassdoor.com/Salary/Barnes-and-Noble-Salaries-E2439.htm",
"Avaya@@www.avaya.com@http://www.glassdoor.com/Salary/Avaya-Salaries-E12121.htm",
"Subway@@www.subway.com@http://www.glassdoor.com/Salary/Subway-Salaries-E2994.htm",
"Aricent@@www.aricent.com@http://www.glassdoor.com/Salary/Aricent-Salaries-E28187.htm",
"Edelman@@www.edelman.com@http://www.glassdoor.com/Salary/Edelman-Salaries-E4608.htm",
"Ford Motor@@www.ford.com@http://www.glassdoor.com/Salary/Ford-Motor-Salaries-E263.htm",
"Samsung Group@@www.samsung.com@http://www.glassdoor.com/Salary/Samsung-Group-Salaries-E3363.htm",
"Wachovia@@www.wachovia.com@http://www.glassdoor.com/Salary/Wachovia-Salaries-E13482.htm",
"Pearson@@www.pearson.com@http://www.glassdoor.com/Salary/Pearson-Salaries-E3322.htm",
"Unilever@@www.unilever.com@http://www.glassdoor.com/Salary/Unilever-Salaries-E3513.htm",
"Kraft Foods@@www.kraft.com@http://www.glassdoor.com/Salary/Kraft-Foods-Salaries-E13294.htm",
"University of Michigan@@www.umich.edu@http://www.glassdoor.com/Salary/University-of-Michigan-Salaries-E3023.htm",
"AIG@@www.aig.com@http://www.glassdoor.com/Salary/AIG-Salaries-E40.htm",
"Agilent Technologies@@www.agilent.com@http://www.glassdoor.com/Salary/Agilent-Technologies-Salaries-E9711.htm",
"Royal Bank of Scotland@@www.rbs.com@http://www.glassdoor.com/Salary/Royal-Bank-of-Scotland-Salaries-E10222.htm",
"Micron Technology@@www.micron.com@http://www.glassdoor.com/Salary/Micron-Technology-Salaries-E1648.htm",
"Nortel Networks@@www.nortel.com@http://www.glassdoor.com/Salary/Nortel-Networks-Salaries-E3497.htm",
"Novartis Pharmaceuticals@@www.pharma.us.novartis.com@http://www.glassdoor.com/Salary/Novartis-Pharmaceuticals-Salaries-E18697.htm",
"CBRE@@www.cbre.com@http://www.glassdoor.com/Salary/CBRE-Salaries-E465818.htm",
"STMicroelectronics@@www.st.com@http://www.glassdoor.com/Salary/STMicroelectronics-Salaries-E3815.htm",
"University of Minnesota@@www.umn.edu@http://www.glassdoor.com/Salary/University-of-Minnesota-Salaries-E3735.htm",
"Citigroup Global Markets@@icg.citi.com@http://www.glassdoor.com/Salary/Citigroup-Global-Markets-Salaries-E584.htm",
"The Coca-Cola Company@@www.thecoca-colacompany.com@http://www.glassdoor.com/Salary/The-Coca-Cola-Company-Salaries-E160.htm",
"IBM Research@@www.research.ibm.com@http://www.glassdoor.com/Salary/IBM-Research-Salaries-E308543.htm",
"BNP Paribas@@www.bnpparibas.com@http://www.glassdoor.com/Salary/BNP-Paribas-Salaries-E10342.htm",
"7-Eleven@@www.7-eleven.com@http://www.glassdoor.com/Salary/7-Eleven-Salaries-E3581.htm",
"Philips Electronics@@www.philips.com@http://www.glassdoor.com/Salary/Philips-Electronics-Salaries-E3496.htm",
"Hyatt@@www.hyatt.com@http://www.glassdoor.com/Salary/Hyatt-Salaries-E2839.htm",
"Lionbridge@@www.lionbridge.com@http://www.glassdoor.com/Salary/Lionbridge-Salaries-E9427.htm",
"SAS Institute@@www.sas.com@http://www.glassdoor.com/Salary/SAS-Institute-Salaries-E3807.htm",
"Houghton Mifflin Harcourt@@www.hmco.com@http://www.glassdoor.com/Salary/Houghton-Mifflin-Harcourt-Salaries-E275.htm",
"US Department of State@@www.careers.state.gov@http://www.glassdoor.com/Salary/US-Department-of-State-Salaries-E32768.htm",
"HCL Infosystems@@www.hclinfosystems.com@http://www.glassdoor.com/Salary/HCL-Infosystems-Salaries-E41919.htm",
"Zara@@www.zara.com@http://www.glassdoor.com/Salary/Zara-Salaries-E17544.htm",
"MassMutual@@www.massmutual.com@http://www.glassdoor.com/Salary/MassMutual-Salaries-E2890.htm",
"Covance@@www.covance.com@http://www.glassdoor.com/Salary/Covance-Salaries-E6758.htm",
"BASF Corporation@@www.basf.us@http://www.glassdoor.com/Salary/BASF-Corporation-Salaries-E4231.htm",
"Western Digital@@www.wdc.com@http://www.glassdoor.com/Salary/Western-Digital-Salaries-E1067.htm",
"Analog Devices@@www.analog.com@http://www.glassdoor.com/Salary/Analog-Devices-Salaries-E49.htm",
"Cold Stone Creamery@@www.coldstonecreamery.com@http://www.glassdoor.com/Salary/Cold-Stone-Creamery-Salaries-E15591.htm",
"Orange Business Services@@www.orange-business.com@http://www.glassdoor.com/Salary/Orange-Business-Services-Salaries-E241093.htm",
"Sony@@www.sony.net@http://www.glassdoor.com/Salary/Sony-Salaries-E3541.htm",
"Estée Lauder@@www.elcompanies.com@http://www.glassdoor.com/Salary/Est%C3%A9e-Lauder-Salaries-E2785.htm",
"Diebold@@www.diebold.com@http://www.glassdoor.com/Salary/Diebold-Salaries-E201.htm",
"Lehman Brothers@@www.lehman.com@http://www.glassdoor.com/Salary/Lehman-Brothers-Salaries-E3565.htm",
"Tyco@@www.tyco.com@http://www.glassdoor.com/Salary/Tyco-Salaries-E681.htm",
"Diageo@@www.diageo.com@http://www.glassdoor.com/Salary/Diageo-Salaries-E7438.htm",
"Self-Employment and Entrepreneur Development Society (SEEDS)@@www.seedsbdc.com@http://www.glassdoor.com/Salary/Self-Employment-and-Entrepreneur-Development-Society-SEEDS-Salaries-E525272.htm",
"Panasonic@@www.panasonic.com@http://www.glassdoor.com/Salary/Panasonic-Salaries-E4279.htm",
"McGraw-Hill Education@@www.mheducation.com@http://www.glassdoor.com/Salary/McGraw-Hill-Education-Salaries-E36749.htm",
"British American Tobacco@@www.bat.com@http://www.glassdoor.com/Salary/British-American-Tobacco-Salaries-E8378.htm",
"Maersk Line@@www.maerskline.com@http://www.glassdoor.com/Salary/Maersk-Line-Salaries-E38791.htm",
"Rovi@@www.rovicorp.com@http://www.glassdoor.com/Salary/Rovi-Salaries-E6664.htm",
"DRS Technologies@@www.drs.com@http://www.glassdoor.com/Salary/DRS-Technologies-Salaries-E840.htm",
"Jabil@@www.jabil.com@http://www.glassdoor.com/Salary/Jabil-Salaries-E2330.htm",
"University of British Columbia@@www.ubc.ca@http://www.glassdoor.com/Salary/University-of-British-Columbia-Salaries-E151190.htm",
"Emerson@@www.emerson.com@http://www.glassdoor.com/Salary/Emerson-Salaries-E225.htm",
"Parsons Brinckerhoff@@www.pbworld.com@http://www.glassdoor.com/Salary/Parsons-Brinckerhoff-Salaries-E4424.htm",
"AIESEC International@@www.aiesec.org@http://www.glassdoor.com/Salary/AIESEC-International-Salaries-E463422.htm",
"Sony Ericsson Mobile-Global@@www.sonyericsson.com@http://www.glassdoor.com/Salary/Sony-Ericsson-Mobile-Global-Salaries-E13532.htm",
"Millward Brown@@www.millwardbrown.com@http://www.glassdoor.com/Salary/Millward-Brown-Salaries-E18702.htm",
"ST Ericsson - Global@@www.stericsson.com@http://www.glassdoor.com/Salary/ST-Ericsson-Global-Salaries-E223315.htm",
"RGP@@careers.rgp.com@http://www.glassdoor.com/Salary/RGP-Salaries-E12624.htm",
"Lawrence Berkeley Lab@@lbl.gov@http://www.glassdoor.com/Salary/Lawrence-Berkeley-Lab-Salaries-E35238.htm",
"Air Liquide@@www.airliquide.com@http://www.glassdoor.com/Salary/Air-Liquide-Salaries-E15075.htm",
"Underwriters Laboratories@@www.ul.com@http://www.glassdoor.com/Salary/Underwriters-Laboratories-Salaries-E3979.htm",
"Gemalto@@www.gemalto.com@http://www.glassdoor.com/Salary/Gemalto-Salaries-E35090.htm",
"Hess Corporation@@www.hess.com@http://www.glassdoor.com/Salary/Hess-Corporation-Salaries-E30.htm",
"Imperial College London@@www.imperial.ac.uk@http://www.glassdoor.com/Salary/Imperial-College-London-Salaries-E36783.htm",
"Misys@@www.misys.co.uk@http://www.glassdoor.com/Salary/Misys-Salaries-E10291.htm",
"Bank Of Tokyo-Mitsubishi UFJ@@www.bk.mufg.jp@http://www.glassdoor.com/Salary/Bank-Of-Tokyo-Mitsubishi-UFJ-Salaries-E240039.htm",
"Sara Lee@@www.saralee.com@http://www.glassdoor.com/Salary/Sara-Lee-Salaries-E586.htm",
"Columbia Sportswear@@www.columbia.com@http://www.glassdoor.com/Salary/Columbia-Sportswear-Salaries-E3853.htm",
"Atmel@@www.atmel.com@http://www.glassdoor.com/Salary/Atmel-Salaries-E1776.htm",
"ABN AMRO@@www.abnamro.com@http://www.glassdoor.com/Salary/ABN-AMRO-Salaries-E10499.htm",
"Novellus@@www.lamresearch.com@http://www.glassdoor.com/Salary/Novellus-Salaries-E1717.htm",
"British Council@@www.britishcouncil.org@http://www.glassdoor.com/Salary/British-Council-Salaries-E117008.htm",
"Qimonda *@@www.qimonda.com@http://www.glassdoor.com/Salary/Qimonda-Salaries-E40858.htm",
"Daymon Worldwide@@www.daymon.com@http://www.glassdoor.com/Salary/Daymon-Worldwide-Salaries-E213870.htm",
"McCann Worldgroup@@www.mccann.com@http://www.glassdoor.com/Salary/McCann-Worldgroup-Salaries-E14074.htm",
"TNS Global@@www.tns-global.com@http://www.glassdoor.com/Salary/TNS-Global-Salaries-E10248.htm",
"Conexant Systems@@www.conexant.com@http://www.glassdoor.com/Salary/Conexant-Systems-Salaries-E8975.htm",
"Nissan@@www.nissan-global.com@http://www.glassdoor.com/Salary/Nissan-Salaries-E3535.htm",
"Allianz Life@@www.allianzlife.com@http://www.glassdoor.com/Salary/Allianz-Life-Salaries-E13810.htm",
"Intersil@@www.intersil.com@http://www.glassdoor.com/Salary/Intersil-Salaries-E11208.htm",
"Nomura International@@www.nomura.com@http://www.glassdoor.com/Salary/Nomura-International-Salaries-E13432.htm",
"LVMH@@www.lvmh.com@http://www.glassdoor.com/Salary/LVMH-Salaries-E3489.htm",
"Crane Aerospace &amp; Electronics@@www.craneae.com@http://www.glassdoor.com/Salary/Crane-Aerospace-and-Electronics-Salaries-E33856.htm",
"Skechers U.S.A.@@www.skx.com@http://www.glassdoor.com/Salary/Skechers-U-S-A-Salaries-E8575.htm",
"Development Dimensions International@@www.ddiworld.com@http://www.glassdoor.com/Salary/Development-Dimensions-International-Salaries-E16088.htm",
"Bayer HealthCare Pharmaceuticals@@pharma.bayer.com@http://www.glassdoor.com/Salary/Bayer-HealthCare-Pharmaceuticals-Salaries-E8480.htm",
"Ogilvy Public Relations@@www.ogilvypr.com@http://www.glassdoor.com/Salary/Ogilvy-Public-Relations-Salaries-E13678.htm",
"MSLGROUP@@www.mslgroup.com@http://www.glassdoor.com/Salary/MSLGROUP-Salaries-E394412.htm",
"Akzo Nobel Decorative Paints@@www.akzonobel.com@http://www.glassdoor.com/Salary/Akzo-Nobel-Decorative-Paints-Salaries-E14552.htm",
"Watson Wyatt@@www.watsonwyatt.com@http://www.glassdoor.com/Salary/Watson-Wyatt-Salaries-E3725.htm",
"Citadel Investment@@www.citadelgroup.com@http://www.glassdoor.com/Salary/Citadel-Investment-Salaries-E14937.htm",
"AbbVie@@abbvie.com@http://www.glassdoor.com/Salary/AbbVie-Salaries-E649837.htm",
"Bombardier Transportation@@www.bombardier.com@http://www.glassdoor.com/Salary/Bombardier-Transportation-Salaries-E242883.htm",
"QIAGEN@@www.qiagen.com@http://www.glassdoor.com/Salary/QIAGEN-Salaries-E6170.htm",
"Norwegian Cruise Line@@www.ncl.com@http://www.glassdoor.com/Salary/Norwegian-Cruise-Line-Salaries-E9937.htm",
"BEA Systems@@www.bea.com@http://www.glassdoor.com/Salary/BEA-Systems-Salaries-E6699.htm",
"MSC.Software@@www.mscsoftware.com@http://www.glassdoor.com/Salary/MSC-Software-Salaries-E931.htm",
"Einfochips@@www.einfochips.com@http://www.glassdoor.com/Salary/Einfochips-Salaries-E130677.htm",
"Interpublic Group@@www.interpublic.com@http://www.glassdoor.com/Salary/Interpublic-Group-Salaries-E358.htm",
"Laird Technologies@@www.lairdtech.com@http://www.glassdoor.com/Salary/Laird-Technologies-Salaries-E15396.htm",
"Rohde &amp; Schwarz@@www.rohde-schwarz.com@http://www.glassdoor.com/Salary/Rohde-and-Schwarz-Salaries-E12926.htm",
"Amkor@@www.amkor.com@http://www.glassdoor.com/Salary/Amkor-Salaries-E6638.htm",
"Foxconn Technology@@www.foxconntech.com.tw@http://www.glassdoor.com/Salary/Foxconn-Technology-Salaries-E41131.htm",
"Wall Street Institute@@www.wallstreetinstitute.com@http://www.glassdoor.com/Salary/Wall-Street-Institute-Salaries-E301258.htm",
"CSR@@www.csr.com@http://www.glassdoor.com/Salary/CSR-Salaries-E12003.htm",
"BASF SE@@www.basf.com@http://www.glassdoor.com/Salary/BASF-SE-Salaries-E3457.htm",
"Ministry of Defence@@www.mod.co.uk@http://www.glassdoor.com/Salary/Ministry-of-Defence-Salaries-E235143.htm",
"ZenithOptimedia@@www.zenithoptimedia.com@http://www.glassdoor.com/Salary/ZenithOptimedia-Salaries-E16006.htm",
"Atheros@@www.qca.qualcomm.com@http://www.glassdoor.com/Salary/Atheros-Salaries-E13698.htm",
"NetIQ@@www.netiq.com@http://www.glassdoor.com/Salary/NetIQ-Salaries-E9371.htm",
"50 Below@@www.arinet.com@http://www.glassdoor.com/Salary/50-Below-Salaries-E297979.htm",
"Fidelity International@@www.fidelity.co.uk@http://www.glassdoor.com/Salary/Fidelity-International-Salaries-E36754.htm",
"Vishay Intertechnology@@www.vishay.com@http://www.glassdoor.com/Salary/Vishay-Intertechnology-Salaries-E706.htm",
"iSoftstone@@www.isoftstone.com@http://www.glassdoor.com/Salary/iSoftstone-Salaries-E158251.htm",
"Newsweek Daily Beast@@www.dailybeast.com@http://www.glassdoor.com/Salary/Newsweek-Daily-Beast-Salaries-E19837.htm",
"Verigy@@www.verigy.com@http://www.glassdoor.com/Salary/Verigy-Salaries-E40792.htm",
"Simmons Bedding@@www.simmons.com@http://www.glassdoor.com/Salary/Simmons-Bedding-Salaries-E5586.htm",
"Bsquare@@www.bsquare.com@http://www.glassdoor.com/Salary/Bsquare-Salaries-E9718.htm",
"OmniVision Technologies@@www.ovt.com@http://www.glassdoor.com/Salary/OmniVision-Technologies-Salaries-E11650.htm",
"MSI@@www.marketstrategies.com@http://www.glassdoor.com/Salary/MSI-Salaries-E15413.htm",
"Mitsubishi@@www.mitsubishicorp.com@http://www.glassdoor.com/Salary/Mitsubishi-Salaries-E7587.htm",
"Mitsui O.S.K. Lines@@www.mol.co.jp@http://www.glassdoor.com/Salary/Mitsui-O-S-K-Lines-Salaries-E8172.htm",
"Oxford University Press@@www.oup.com@http://www.glassdoor.com/Salary/Oxford-University-Press-Salaries-E587409.htm",
"Parature@@www.parature.com@http://www.glassdoor.com/Salary/Parature-Salaries-E33680.htm",
"Louis Vuitton@@www.louisvuitton.com@http://www.glassdoor.com/Salary/Louis-Vuitton-Salaries-E667150.htm",
"NEC Laboratories America, Inc.@@www.nec-labs.com@http://www.glassdoor.com/Salary/NEC-Laboratories-America-Inc-Salaries-E158697.htm",
"Cognex@@www.cognex.com@http://www.glassdoor.com/Salary/Cognex-Salaries-E1273.htm",
"GfK AG@@www.gfk.com@http://www.glassdoor.com/Salary/GfK-AG-Salaries-E12882.htm",
"Symbio@@www.symbio.com@http://www.glassdoor.com/Salary/Symbio-Salaries-E32387.htm",
"O2Micro@@www.o2micro.com@http://www.glassdoor.com/Salary/O2Micro-Salaries-E12520.htm",
"Cambridge Silicon Radio@@www.csr.com@http://www.glassdoor.com/Salary/Cambridge-Silicon-Radio-Salaries-E368235.htm",
"Wooga@@www.wooga.com@http://www.glassdoor.com/Salary/Wooga-Salaries-E421202.htm",
"STATS ChipPAC@@www.statschippac.com@http://www.glassdoor.com/Salary/STATS-ChipPAC-Salaries-E11337.htm",
"CEI@@www.ceiamerica.com@http://www.glassdoor.com/Salary/CEI-Salaries-E14778.htm",
"EBSCO@@www.ebscoind.com@http://www.glassdoor.com/Salary/EBSCO-Salaries-E6624.htm",
"Manpower Professional@@None@http://www.glassdoor.com/Salary/Manpower-Professional-Salaries-E451264.htm",
"Schroders@@www.schroders.com@http://www.glassdoor.com/Salary/Schroders-Salaries-E10512.htm",
"Acer America@@www.acer.us@http://www.glassdoor.com/Salary/Acer-America-Salaries-E16129.htm",
"Samsonite@@corporate.samsonite.com@http://www.glassdoor.com/Salary/Samsonite-Salaries-E2721.htm",
"Department of Health UK@@www.dh.gov.uk@http://www.glassdoor.com/Salary/Department-of-Health-UK-Salaries-E230892.htm",
"Avocent@@www.avocent.com@http://www.glassdoor.com/Salary/Avocent-Salaries-E6626.htm",
"Mycom@@www.mycom-int.com@http://www.glassdoor.com/Salary/Mycom-Salaries-E217725.htm",
"Electro Scientific Industries@@www.esi.com@http://www.glassdoor.com/Salary/Electro-Scientific-Industries-Salaries-E1365.htm",
"SodaStream@@www.sodastream.com@http://www.glassdoor.com/Salary/SodaStream-Salaries-E354698.htm",
"BYD@@www.byd.com.cn@http://www.glassdoor.com/Salary/BYD-Salaries-E41020.htm",
"HRnet One Pt@@www.hrnetone.com@http://www.glassdoor.com/Salary/HRnet-One-Pt-Salaries-E502980.htm",
"Partek@@www.partek.com@http://www.glassdoor.com/Salary/Partek-Salaries-E288907.htm",
"Pinkerton@@www.pinkerton.com@http://www.glassdoor.com/Salary/Pinkerton-Salaries-E314502.htm",
"BridgeLux@@www.bridgelux.com@http://www.glassdoor.com/Salary/BridgeLux-Salaries-E263874.htm",
"TCI@@www.qodm.com@http://www.glassdoor.com/Salary/TCI-Salaries-E368913.htm",
"Ambarella@@www.ambarella.com@http://www.glassdoor.com/Salary/Ambarella-Salaries-E263590.htm",
"Toro@@www.toro-asia.com@http://www.glassdoor.com/Salary/Toro-Salaries-E428180.htm",
"The Chop House@@www.connorconcepts.com@http://www.glassdoor.com/Salary/The-Chop-House-Salaries-E216891.htm",
"Samsung SDI@@www.samsungsdi.com@http://www.glassdoor.com/Salary/Samsung-SDI-Salaries-E40761.htm",
"Time Technoplast@@www.timetechnoplast.com@http://www.glassdoor.com/Salary/Time-Technoplast-Salaries-E510855.htm",
"DKSH Holding@@www.dksh.com@http://www.glassdoor.com/Salary/DKSH-Holding-Salaries-E24749.htm",
"AVerMedia@@www.avermedia.com@http://www.glassdoor.com/Salary/AVerMedia-Salaries-E9143.htm",
"Phoenix Suns@@www.nba.com@http://www.glassdoor.com/Salary/Phoenix-Suns-Salaries-E5282.htm",
"NEC@@nec-eg.com@http://www.glassdoor.com/Salary/NEC-Salaries-E724815.htm",
"First Commercial Bank@@www.1stcommercialbank.com@http://www.glassdoor.com/Salary/First-Commercial-Bank-Salaries-E157067.htm",
"TheMarkets.com@@www.themarkets.com@http://www.glassdoor.com/Salary/TheMarkets-com-Salaries-E266496.htm",
"NNR@@www.nnrusa.com@http://www.glassdoor.com/Salary/NNR-Salaries-E238452.htm",
"SRAM@@www.sram.com@http://www.glassdoor.com/Salary/SRAM-Salaries-E14880.htm",
"Primax@@www.primax.com.tw@http://www.glassdoor.com/Salary/Primax-Salaries-E224024.htm",
"Kaplan Tutoring@@www.kaplantutoring.com@http://www.glassdoor.com/Salary/Kaplan-Tutoring-Salaries-E245643.htm",
"Shane English@@www.shane.com.cn@http://www.glassdoor.com/Salary/Shane-English-Salaries-E246479.htm",
"ING Funds@@www.ingfunds.com@http://www.glassdoor.com/Salary/ING-Funds-Salaries-E261454.htm",
"IEI Technologies@@www.ieiworld.com@http://www.glassdoor.com/Salary/IEI-Technologies-Salaries-E283740.htm",
"CMC Magnetics Corp@@www.cmcdisc.com@http://www.glassdoor.com/Salary/CMC-Magnetics-Corp-Salaries-E15750.htm",
"TPV Technology@@www.tpvholdings.com@http://www.glassdoor.com/Salary/TPV-Technology-Salaries-E37710.htm",
"NetBase Solutions@@www.netbase.com@http://www.glassdoor.com/Salary/NetBase-Solutions-Salaries-E433313.htm",
"TAWA Supermarket@@www.99ranch.com@http://www.glassdoor.com/Salary/TAWA-Supermarket-Salaries-E9545.htm",
"E Ink@@www.eink.com@http://www.glassdoor.com/Salary/E-Ink-Salaries-E11383.htm",
"Fubon Financial@@www.fubon.com@http://www.glassdoor.com/Salary/Fubon-Financial-Salaries-E26900.htm",
"3i-Mind@@www.3i-mind.com@http://www.glassdoor.com/Salary/3i-Mind-Salaries-E549546.htm",
"MPI@@www.mpiproducts.com@http://www.glassdoor.com/Salary/MPI-Salaries-E259118.htm",
"Infortrend@@www.infortrend.com@http://www.glassdoor.com/Salary/Infortrend-Salaries-E264011.htm",
"Nanya@@www.nanya.com@http://www.glassdoor.com/Salary/Nanya-Salaries-E35089.htm",
"First International Computer@@www.fic.com.tw@http://www.glassdoor.com/Salary/First-International-Computer-Salaries-E7236.htm",
"ProTech Systems Group, Inc.@@www.psgi.net@http://www.glassdoor.com/Salary/ProTech-Systems-Group-Inc-Salaries-E218213.htm",
"HB Performance Systems@@www.hbpsi.com@http://www.glassdoor.com/Salary/HB-Performance-Systems-Salaries-E254113.htm",
"Coretronic@@www.coretronic.com@http://www.glassdoor.com/Salary/Coretronic-Salaries-E41172.htm",
"Foxlink International@@www.cupic.com@http://www.glassdoor.com/Salary/Foxlink-International-Salaries-E290007.htm",
"Conacyt@@www.conacyt.mx@http://www.glassdoor.com/Salary/Conacyt-Salaries-E323166.htm",
"CDE@@www.centrotherm-pv.com@http://www.glassdoor.com/Reviews/CDE-Reviews-E422076.htm",
"Infortrend@@www.infortrend.com@http://www.glassdoor.com/Salary/Infortrend-Salaries-E264011.htm",
"Nanya@@www.nanya.com@http://www.glassdoor.com/Salary/Nanya-Salaries-E35089.htm",
"First International Computer@@www.fic.com.tw@http://www.glassdoor.com/Salary/First-International-Computer-Salaries-E7236.htm",
"ProTech Systems Group, Inc.@@www.psgi.net@http://www.glassdoor.com/Salary/ProTech-Systems-Group-Inc-Salaries-E218213.htm",
"HB Performance Systems@@www.hbpsi.com@http://www.glassdoor.com/Salary/HB-Performance-Systems-Salaries-E254113.htm",
"Coretronic@@www.coretronic.com@http://www.glassdoor.com/Salary/Coretronic-Salaries-E41172.htm",
"Foxlink International@@www.cupic.com@http://www.glassdoor.com/Salary/Foxlink-International-Salaries-E290007.htm",
"Conacyt@@www.conacyt.mx@http://www.glassdoor.com/Salary/Conacyt-Salaries-E323166.htm",
"CDE@@www.centrotherm-pv.com@http://www.glassdoor.com/Reviews/CDE-Reviews-E422076.htm",
"Infortrend@@www.infortrend.com@http://www.glassdoor.com/Salary/Infortrend-Salaries-E264011.htm",
"Nanya@@www.nanya.com@http://www.glassdoor.com/Salary/Nanya-Salaries-E35089.htm",
"First International Computer@@www.fic.com.tw@http://www.glassdoor.com/Salary/First-International-Computer-Salaries-E7236.htm",
"ProTech Systems Group, Inc.@@www.psgi.net@http://www.glassdoor.com/Salary/ProTech-Systems-Group-Inc-Salaries-E218213.htm",
"HB Performance Systems@@www.hbpsi.com@http://www.glassdoor.com/Salary/HB-Performance-Systems-Salaries-E254113.htm",
"Coretronic@@www.coretronic.com@http://www.glassdoor.com/Salary/Coretronic-Salaries-E41172.htm",
"Foxlink International@@www.cupic.com@http://www.glassdoor.com/Salary/Foxlink-International-Salaries-E290007.htm",
"Conacyt@@www.conacyt.mx@http://www.glassdoor.com/Salary/Conacyt-Salaries-E323166.htm",
"CDE@@www.centrotherm-pv.com@http://www.glassdoor.com/Reviews/CDE-Reviews-E422076.htm",
"Infortrend@@www.infortrend.com@http://www.glassdoor.com/Salary/Infortrend-Salaries-E264011.htm",
"Nanya@@www.nanya.com@http://www.glassdoor.com/Salary/Nanya-Salaries-E35089.htm",
"First International Computer@@www.fic.com.tw@http://www.glassdoor.com/Salary/First-International-Computer-Salaries-E7236.htm",
"ProTech Systems Group, Inc.@@www.psgi.net@http://www.glassdoor.com/Salary/ProTech-Systems-Group-Inc-Salaries-E218213.htm",
"HB Performance Systems@@www.hbpsi.com@http://www.glassdoor.com/Salary/HB-Performance-Systems-Salaries-E254113.htm",
"Coretronic@@www.coretronic.com@http://www.glassdoor.com/Salary/Coretronic-Salaries-E41172.htm",
"Foxlink International@@www.cupic.com@http://www.glassdoor.com/Salary/Foxlink-International-Salaries-E290007.htm",
"Conacyt@@www.conacyt.mx@http://www.glassdoor.com/Salary/Conacyt-Salaries-E323166.htm",
"CDE@@www.centrotherm-pv.com@http://www.glassdoor.com/Reviews/CDE-Reviews-E422076.htm",
"Taikoo Motors@@Www.taikoomotors.com.tw@http://www.glassdoor.com/Reviews/Taikoo-Motors-Reviews-E418156.htm",
"Kang Chiao Bilingual School@@www.kcbs.ntpc.edu.tw@http://www.glassdoor.com/Reviews/Kang-Chiao-Bilingual-School-Reviews-E696009.htm",
"TTY Biopharm@@www.tty.com.tw@http://www.glassdoor.com/Salary/TTY-Biopharm-Salaries-E237370.htm",
"ShinKong Mitsukoshi@@www.skm.com.tw@http://www.glassdoor.com/Reviews/ShinKong-Mitsukoshi-Reviews-E413881.htm",
"Dynacolor@@www.dynacolor.com.tw@http://www.glassdoor.com/Reviews/Dynacolor-Reviews-E662854.htm",
"Amic Technology@@www.amictechnology.com@http://www.glassdoor.com/Salary/Amic-Technology-Salaries-E282658.htm",
"Mstar@@www.mstar2.net@http://www.glassdoor.com/Reviews/Mstar-Reviews-E306835.htm",
"Senao@@www.senao.com@http://www.glassdoor.com/Salary/Senao-Salaries-E412363.htm",
"Evergreen Logistics@@www.evergreen-logistics.com@http://www.glassdoor.com/Reviews/Evergreen-Logistics-Reviews-E452060.htm",
"TPKI@@www.tpki.com.ph@http://www.glassdoor.com/Salary/TPKI-Salaries-E535402.htm",
"Taipei Veterans General Hospital@@www.vghtpe.gov.tw@http://www.glassdoor.com/Salary/Taipei-Veterans-General-Hospital-Salaries-E676707.htm",
"RD Management@@www.rdmanagement.com@http://www.glassdoor.com/Salary/RD-Management-Salaries-E24795.htm",
"Cameo@@www.mitac-mtc.com.tw@http://www.glassdoor.com/Salary/Cameo-Salaries-E36586.htm",
"MiTAC Technology@@www.mio.com@http://www.glassdoor.com/Reviews/MiTAC-Technology-Reviews-E41119.htm",
"Mio Technology@@www.edyna.com@http://www.glassdoor.com/Salary/Mio-Technology-Salaries-E134598.htm",
"eDynamics@@www.cywee.com@http://www.glassdoor.com/Reviews/eDynamics-Reviews-E141252.htm",
"CyWee Group@@www.morrisonexpress.com@http://www.glassdoor.com/Salary/CyWee-Group-Salaries-E256031.htm",
"Morrison Express Corp. (U.S.A.)@@www.ralinktech.com@http://www.glassdoor.com/Salary/Morrison-Express-Corp-U-S-A-Salaries-E266549.htm",
"ralink technology Corp.@@www.gcctechllc.com@http://www.glassdoor.com/Salary/ralink-technology-Corp-Salaries-E270455.htm",
"The Saxoncourt Group@@www.saxoncourt.net@http://www.glassdoor.com/Salary/The-Saxoncourt-Group-Salaries-E600614.htm",
"SUNON Group@@www.sunon.com@http://www.glassdoor.com/Salary/SUNON-Group-Salaries-E631228.htm",
"Foxlink Group@@www.foxlink.com@http://www.glassdoor.com/Salary/Foxlink-Group-Salaries-E665452.htm",
"Samirian Chemicals@@www.samirian.com@http://www.glassdoor.com/Salary/Samirian-Chemicals-Salaries-E694559.htm",
"Taiwan Business Bank@@www.tbb.com.tw@http://www.glassdoor.com/Salary/Taiwan-Business-Bank-Salaries-E40492.htm",
"Etron@@www.etron.com@http://www.glassdoor.com/Salary/Etron-Salaries-E155346.htm",
"Siliconware@@www.spilca.com@http://www.glassdoor.com/Salary/Siliconware-Salaries-E266487.htm",
"Tecom Group@@www.tecomgroup.com@http://www.glassdoor.com/Salary/Tecom-Group-Salaries-E271132.htm",
"Emerging Markets Management@@www.emi-emm.com@http://www.glassdoor.com/Salary/Emerging-Markets-Management-Salaries-E283449.htm",
"Syndiant@@www.syndiant.com@http://www.glassdoor.com/Salary/Syndiant-Salaries-E283934.htm",
"Gjun Information Company@@www.pcschool.tv@http://www.glassdoor.com/Salary/Gjun-Information-Company-Salaries-E307470.htm",
"Cohen Milstein Sellers &amp; Toll@@cohenmilstein.com@http://www.glassdoor.com/Salary/Cohen-Milstein-Sellers-and-Toll-Salaries-E404496.htm",
"Tong Hsing Electronic Industries@@www.theil.com.tw@http://www.glassdoor.com/Salary/Tong-Hsing-Electronic-Industries-Salaries-E601287.htm",
"Tatung@@www.tatung.com.tw@http://www.glassdoor.com/Salary/Tatung-Salaries-E3808.htm",
"InfoValue@@www.infovalue.com@http://www.glassdoor.com/Salary/InfoValue-Salaries-E10032.htm",
"Fetl@@www.fenc.com@http://www.glassdoor.com/Reviews/Fetl-Reviews-E24954.htm",
"Chang Hwa Bank@@www.chb.com.tw@http://www.glassdoor.com/Salary/Chang-Hwa-Bank-Salaries-E40438.htm",
"E.Sun@@www.esunfhc.com.tw@http://www.glassdoor.com/Salary/E-Sun-Salaries-E40621.htm",
"Far Eastern Department Stores@@www.feds.com.tw@http://www.glassdoor.com/Reviews/Far-Eastern-Department-Stores-Reviews-E41216.htm",
"Era Ogilvy@@www.eraogilvy.com@http://www.glassdoor.com/Reviews/Era-Ogilvy-Reviews-E255236.htm",
"Heaven@@www.heavendayspa.com@http://www.glassdoor.com/Salary/Heaven-Salaries-E289966.htm",
"Cathay United Bank@@www.cathaybk.com.tw@http://www.glassdoor.com/Salary/Cathay-United-Bank-Salaries-E308964.htm",
"PixArt@@www.pixart.com.tw@http://www.glassdoor.com/Salary/PixArt-Salaries-E317738.htm",
"Create Electronic Optical@@www.create-eop.com.tw@http://www.glassdoor.com/Reviews/Create-Electronic-Optical-Reviews-E391424.htm",
"Koncept@@www.importgenius.com@http://www.glassdoor.com/Reviews/Koncept-Reviews-E392484.htm",
"RealSun@@www.realsun.com.tw@http://www.glassdoor.com/Reviews/RealSun-Reviews-E397170.htm",
"Andes Technology@@www.andestech.com@http://www.glassdoor.com/Reviews/Andes-Technology-Reviews-E398907.htm",
"VisEra Technologies@@www.viseratech.com@http://www.glassdoor.com/Reviews/VisEra-Technologies-Reviews-E402124.htm",
"Realtek@瑞昱半導體@http://www.realtek.com@http://www.glassdoor.com/Salary/Realtek-Salaries-E444509.htm",
"Logic Art Automation@@www.logicart.com.tw@http://www.glassdoor.com/Reviews/Logic-Art-Automation-Reviews-E459464.htm",
"Republic of China Navy@@www.taiwanairpower.org@http://www.glassdoor.com/Reviews/Republic-of-China-Navy-Reviews-E473709.htm",
"Bios Monthly@@www.biosmonthly.com@http://www.glassdoor.com/Reviews/Bios-Monthly-Reviews-E539683.htm",
"I-Mei Multimedia e-Content Production@@www.i-me-i.com@http://www.glassdoor.com/Reviews/I-Mei-Multimedia-e-Content-Production-Reviews-E559793.htm",
"GIGASTORAGE@@www.gigastorage.tw@http://www.glassdoor.com/Reviews/GIGASTORAGE-Reviews-E560456.htm",
"Union Genius Computer@@www.ugcc.com.tw@http://www.glassdoor.com/Reviews/Union-Genius-Computer-Reviews-E564917.htm",
"E&amp;C Engineering@@www.eandc.com.tw@http://www.glassdoor.com/Salary/E-and-C-Engineering-Salaries-E593378.htm",
"Estinet Technologies@@www.estinet.com@http://www.glassdoor.com/Reviews/Estinet-Technologies-Reviews-E599590.htm",
"TNS Taiwan@@www.tns-global.com.tw@http://www.glassdoor.com/Salary/TNS-Taiwan-Salaries-E602514.htm",
"Elysium (Taiwan)@@www.elysiummotor.com@http://www.glassdoor.com/Reviews/Elysium-Taiwan-Reviews-E603436.htm",
"Vibration Source Technology@@www.vib-source.com.tw@http://www.glassdoor.com/Reviews/Vibration-Source-Technology-Reviews-E605249.htm",
"XPEC@@www.xpec.com@http://www.glassdoor.com/Salary/XPEC-Salaries-E610528.htm",
"Hitron Technologies@@www.hitrontech.com@http://www.glassdoor.com/Salary/Hitron-Technologies-Salaries-E636232.htm",
"Epoch Foundation@@www.epoch.org.tw@http://www.glassdoor.com/Reviews/Epoch-Foundation-Reviews-E663294.htm",
"ELAN Microelectronic@@www.emc.com.tw@http://www.glassdoor.com/Reviews/ELAN-Microelectronic-Reviews-E682058.htm",
"EGAT@@www.egat.com.tw@http://www.glassdoor.com/Reviews/EGAT-Reviews-E689418.htm",
"Department of Education, Taipei City Government@@www.tp.edu.tw@http://www.glassdoor.com/Salary/Department-of-Education-Taipei-City-Government-Salaries-E706877.htm",
"uPI Semiconductor@@www.upi-semi.com@http://www.glassdoor.com/Reviews/uPI-Semiconductor-Reviews-E711359.htm",
"Genesys Logic@@www.genesyslogic.com.tw@http://www.glassdoor.com/Reviews/Genesys-Logic-Reviews-E711648.htm",
"Muzee@@en.muzee.net@http://www.glassdoor.com/Reviews/Muzee-Reviews-E711766.htm",
"Nature's Value@@www.naturesvalue.com@http://www.glassdoor.com/Salary/Nature-s-Value-Salaries-E726910.htm",
"GIGO@@www.gigo.com.tw@http://www.glassdoor.com/Salary/GIGO-Salaries-E744984.htm",
"AccessPR@@www.accesspr.com.tw@http://www.glassdoor.com/Salary/AccessPR-Salaries-E746072.htm",
"EZTABLE@@www.eztable.com.tw@http://www.glassdoor.com/Reviews/EZTABLE-Reviews-E749562.htm",
"Learning Digital@@www.learningdigital.com@http://www.glassdoor.com/Reviews/Learning-Digital-Reviews-E761383.htm",
"Solas@@www.cathaylife.com.tw@http://www.glassdoor.com/Reviews/Solas-Reviews-E774451.htm",
"Cathay Life Insurance@@www.csc.com.tw@http://www.glassdoor.com/Salary/Cathay-Life-Insurance-Salaries-E7663.htm",
"China Steel@@www.inotera.com@http://www.glassdoor.com/Salary/China-Steel-Salaries-E8296.htm",
"Inotera Memories@@www.tcssh.tc.edu.tw@http://www.glassdoor.com/Reviews/Inotera-Memories-Reviews-E43352.htm",
"National Taichung Second Senior High School@@www.plustek.com@http://www.glassdoor.com/Salary/National-Taichung-Second-Senior-High-School-Salaries-E193949.htm",
"Epistar@@www.epistar.com.tw@http://www.glassdoor.com/Salary/Epistar-Salaries-E327834.htm",
"GSiMedia@@www.gsi-media.com@http://www.glassdoor.com/Reviews/GSiMedia-Reviews-E336658.htm",
"iaSolution@@www.iasolution.net@http://www.glassdoor.com/Reviews/iaSolution-Reviews-E394097.htm",
"Tunghai University@@www.thu.edu.tw@http://www.glassdoor.com/Reviews/Tunghai-University-Reviews-E394508.htm",
"CHUNGHWA TELECOM GLOBAL@@www.chtglobal.com@http://www.glassdoor.com/Salary/CHUNGHWA-TELECOM-GLOBAL-Salaries-E430283.htm",
"ZK Group@@www.zkadvertisingng.com@http://www.glassdoor.com/Reviews/ZK-Group-Reviews-E443040.htm",
"Berkeley BIGC@@www.bigc.com.tw@http://www.glassdoor.com/Reviews/Berkeley-BIGC-Reviews-E460047.htm",
"MissionCare@@www.missioncare.com.tw@http://www.glassdoor.com/Reviews/MissionCare-Reviews-E499868.htm",
"Daxin Materials@@www.daxinmat.com@http://www.glassdoor.com/Reviews/Daxin-Materials-Reviews-E526540.htm",
"China Trust Commercial Bank@@www.chinatrust.com.tw@http://www.glassdoor.com/Reviews/China-Trust-Commercial-Bank-Reviews-E548581.htm",
"Evergreen Wine@@www.evergreet.com.tw@http://www.glassdoor.com/Reviews/Evergreen-Wine-Reviews-E549800.htm",
"Giga@@www.giga.co.il@http://www.glassdoor.com/Salary/Giga-Salaries-E554036.htm",
"Peiyu Plastics@@www.pypc.com@http://www.glassdoor.com/Reviews/Peiyu-Plastics-Reviews-E560793.htm",
"EICC@@www.eicc.info@http://www.glassdoor.com/Reviews/EICC-Reviews-E562334.htm",
"K&amp;K Foods@@www.geovision.com.tw@http://www.glassdoor.com/Reviews/K-and-K-Foods-Reviews-E582063.htm",
"Geovision (Taiwan)@@www.pti.com.tw@http://www.glassdoor.com/Salary/Geovision-Taiwan-Salaries-E591096.htm",
"Powertech Technology@@www.shininggroup.com.tw@http://www.glassdoor.com/Salary/Powertech-Technology-Salaries-E592966.htm",
"Shining Group@@www.alliance-gt.com@http://www.glassdoor.com/Reviews/Shining-Group-Reviews-E606324.htm",
"Alliance Global Technology@@www.payeasy.com.tw@http://www.glassdoor.com/Reviews/Alliance-Global-Technology-Reviews-E611040.htm",
"FSP Group@@www.fsp-group.com@http://www.glassdoor.com/Reviews/FSP-Group-Reviews-E620121.htm",
"Intel-NTU Connected Context Computing Center@@ccc.ntu.edu.tw@http://www.glassdoor.com/Salary/Intel-NTU-Connected-Context-Computing-Center-Salaries-E620177.htm",
"Etrovision Technology@@www.etrovision.com@http://www.glassdoor.com/Salary/Etrovision-Technology-Salaries-E625199.htm",
"National Chung Hsing University@@www.nchu.edu.tw@http://www.glassdoor.com/Reviews/National-Chung-Hsing-University-Reviews-E640315.htm",
"Dimension Computer Technology@@www.dimension.com.tw@http://www.glassdoor.com/Reviews/Dimension-Computer-Technology-Reviews-E665745.htm",
"TC Merica English Institute@@www.mericatc.com.tw@http://www.glassdoor.com/Reviews/TC-Merica-English-Institute-Reviews-E666602.htm",
"Sinqual Technology@@www.magstore.com.au@http://www.glassdoor.com/Reviews/Sinqual-Technology-Reviews-E669696.htm",
"Express Media Group@@www.cre8-designstudio.com@http://www.glassdoor.com/Reviews/Express-Media-Group-Reviews-E673273.htm",
"Cre8 Design Studio@@www.qisda.com@http://www.glassdoor.com/Salary/Cre8-Design-Studio-Salaries-E677669.htm",
"Trico Realty@@www.tricorealty.com@http://www.glassdoor.com/Reviews/Trico-Realty-Reviews-E687733.htm",
"Resume Companion@@resumecompanion.com@http://www.glassdoor.com/Reviews/Resume-Companion-Reviews-E691748.htm",
"Kloudian@@www.kloudian.com@http://www.glassdoor.com/Reviews/Kloudian-Reviews-E723245.htm",
"Dapa International Tours@@25sprout.com@http://www.glassdoor.com/Reviews/Dapa-International-Tours-Reviews-E732676.htm",
"25sprout@@chuluranch.com@http://www.glassdoor.com/Reviews/25sprout-Reviews-E743146.htm",
"Chu Lu Ranch@@www.csd.org.tw@http://www.glassdoor.com/Salary/Chu-Lu-Ranch-Salaries-E744185.htm",
"CSD@@www.sonix.com.tw@http://www.glassdoor.com/Reviews/CSD-Reviews-E747973.htm",
"Sonix@@www.win-way.com.tw@http://www.glassdoor.com/Reviews/Sonix-Reviews-E748052.htm",
"Win-Way Advance Technology@@en.ncnu.edu.tw@http://www.glassdoor.com/Salary/Win-Way-Advance-Technology-Salaries-E749217.htm",
"Sunplus@@w3.sunplus.com@http://www.glassdoor.com/Salary/Sunplus-Salaries-E25918.htm",
"Inventec Besta@@www.besta.com.tw@http://www.glassdoor.com/Salary/Inventec-Besta-Salaries-E142885.htm",
"Fortunengine.com@@www.fortunengine.com@http://www.glassdoor.com/Reviews/Fortunengine-com-Reviews-E212530.htm",
"FIH@@www.fih.dk@http://www.glassdoor.com/Salary/FIH-Salaries-E230256.htm",
"National Nano Device Labtory@@www.ndl.org.tw@http://www.glassdoor.com/Salary/National-Nano-Device-Labtory-Salaries-E238839.htm",
"Hontai Life@@www.hontai.com.tw@http://www.glassdoor.com/Salary/Hontai-Life-Salaries-E340903.htm",
"Qpixel Technology@@www.hwh.edu.tw@http://www.glassdoor.com/Salary/Qpixel-Technology-Salaries-E351144.htm",
"Hwa-Hsia Institute of Technology@@www.fesc.com.tw@http://www.glassdoor.com/Reviews/Hwa-Hsia-Institute-of-Technology-Reviews-E352496.htm",
"FeSC@@www.armorize.com@http://www.glassdoor.com/Reviews/FeSC-Reviews-E355149.htm",
"Loyal Group@@www.loyal.com.tw@http://www.glassdoor.com/Reviews/Loyal-Group-Reviews-E363025.htm",
"Data Systems Consulting@@www.dsc.com.tw@http://www.glassdoor.com/Salary/Data-Systems-Consulting-Salaries-E365405.htm",
"Powerchip@@www.powerchip.com@http://www.glassdoor.com/Reviews/Powerchip-Reviews-E370046.htm",
"Synmosa@@www.synmosa.com.tw@http://www.glassdoor.com/Reviews/Synmosa-Reviews-E415563.htm",
"Water Start@@water-start.net@http://www.glassdoor.com/Reviews/Water-Start-Reviews-E418197.htm",
"Tempress Systems@@www.tempress.nl@http://www.glassdoor.com/Reviews/Tempress-Systems-Reviews-E419585.htm",
"Unimicron Technology@@www.unimicron.com@http://www.glassdoor.com/Reviews/Unimicron-Technology-Reviews-E437096.htm",
"TrueTel Communications@@www.truetel.com@http://www.glassdoor.com/Reviews/TrueTel-Communications-Reviews-E467447.htm",
"Welfund Company@@www.welfund.com.tw@http://www.glassdoor.com/Reviews/Welfund-Company-Reviews-E489078.htm",
"Loyal Group@@www.loyal.com.tw@http://www.glassdoor.com/Reviews/Loyal-Group-Reviews-E363025.htm",
"Data Systems Consulting@@www.dsc.com.tw@http://www.glassdoor.com/Salary/Data-Systems-Consulting-Salaries-E365405.htm",
"Powerchip@@www.powerchip.com@http://www.glassdoor.com/Reviews/Powerchip-Reviews-E370046.htm",
"Synmosa@@www.synmosa.com.tw@http://www.glassdoor.com/Reviews/Synmosa-Reviews-E415563.htm",
"Water Start@@water-start.net@http://www.glassdoor.com/Reviews/Water-Start-Reviews-E418197.htm",
"Tempress Systems@@www.tempress.nl@http://www.glassdoor.com/Reviews/Tempress-Systems-Reviews-E419585.htm",
"Unimicron Technology@@www.unimicron.com@http://www.glassdoor.com/Reviews/Unimicron-Technology-Reviews-E437096.htm",
"TrueTel Communications@@www.truetel.com@http://www.glassdoor.com/Reviews/TrueTel-Communications-Reviews-E467447.htm",
"Welfund Company@@www.welfund.com.tw@http://www.glassdoor.com/Reviews/Welfund-Company-Reviews-E489078.htm",
"King Yuan Electronics@@www.kyec.com.tw@http://www.glassdoor.com/Reviews/King-Yuan-Electronics-Reviews-E499110.htm",
"Atlanta Radio Theatre Company@@www.artc.org@http://www.glassdoor.com/Reviews/Atlanta-Radio-Theatre-Company-Reviews-E561773.htm",
"Kingyoup Enterprises@@www.kingyoup.com.tw@http://www.glassdoor.com/Reviews/Kingyoup-Enterprises-Reviews-E588826.htm",
"Silitech Technology@@www.silitech.com@http://www.glassdoor.com/Reviews/Silitech-Technology-Reviews-E588929.htm",
"Samwell Group@@www.samwellg.com@http://www.glassdoor.com/Reviews/Samwell-Group-Reviews-E601678.htm",
"I-Shou University@@www.isu.edu.tw@http://www.glassdoor.com/Reviews/I-Shou-University-Reviews-E603396.htm",
"Lung TEH Shipbuilding@@www.lts.com.tw@http://www.glassdoor.com/Reviews/Lung-TEH-Shipbuilding-Reviews-E610726.htm",
"Makalot Industrial@@www.makalot.com.tw@http://www.glassdoor.com/Reviews/Makalot-Industrial-Reviews-E615732.htm",
"Vega Force Company@@www.gb-tech.com.tw@http://www.glassdoor.com/Reviews/Vega-Force-Company-Reviews-E617493.htm",
"Gseo@@www.gseo.com@http://www.glassdoor.com/Reviews/Gseo-Reviews-E620113.htm",
"Nefful Taiwan@@www.nefful.com.tw@http://www.glassdoor.com/Reviews/Nefful-Taiwan-Reviews-E646701.htm",
"Rei Ting International@@www.reiting.com.tw@http://www.glassdoor.com/Salary/Rei-Ting-International-Salaries-E654137.htm",
"National Chung Cheng University@@www.ccu.edu.tw@http://www.glassdoor.com/Reviews/National-Chung-Cheng-University-Reviews-E659673.htm",
"Taiwan Public Television Service@@www.pts.org.tw@http://www.glassdoor.com/Reviews/Taiwan-Public-Television-Service-Reviews-E661956.htm",
"Asian Institute of Tele-Surgery@@aits.tw@http://www.glassdoor.com/Reviews/Asian-Institute-of-Tele-Surgery-Reviews-E664563.htm",
"Yuan Chiao Englsih School@@www.yuanchiaoschool.com.tw@http://www.glassdoor.com/Salary/Yuan-Chiao-Englsih-School-Salaries-E668221.htm",
"Pinshine@@www.pinshine.com@http://www.glassdoor.com/Reviews/Pinshine-Reviews-E676410.htm",
"HMD Biomedical@@www.hmdbio.com@http://www.glassdoor.com/Salary/HMD-Biomedical-Salaries-E685972.htm",
"Mainland Affairs Council@@www.mac.gov.tw@http://www.glassdoor.com/Salary/Mainland-Affairs-Council-Salaries-E686683.htm",
"The White Rabbit Entertainment@@www.twrglobal.com@http://www.glassdoor.com/Reviews/The-White-Rabbit-Entertainment-Reviews-E713001.htm",
"EXCELL@@www.excell-scale.com@http://www.glassdoor.com/Salary/EXCELL-Salaries-E727108.htm",
"Sunny Bank@@www.sunnybank.com.tw@http://www.glassdoor.com/Reviews/Sunny-Bank-Reviews-E730998.htm",
"TrueLight@@www.truelight.com.tw@http://www.glassdoor.com/Reviews/TrueLight-Reviews-E735082.htm",
"Sperocode@@sperocode.org@http://www.glassdoor.com/Reviews/Sperocode-Reviews-E740602.htm",
"Kutai Electronics@@www.kutai.com.tw@http://www.glassdoor.com/Salary/Kutai-Electronics-Salaries-E745893.htm",
"International Integrated Systems@@www.iisigroup.com@http://www.glassdoor.com/Salary/International-Integrated-Systems-Salaries-E751380.htm",
"Ministry of Economic Affairs, Taiwan@@www.moea.gov.tw@http://www.glassdoor.com/Reviews/Ministry-of-Economic-Affairs-Taiwan-Reviews-E763463.htm",
"JinLin Electric Co.@@www.jinlin.com.tw@http://www.glassdoor.com/Reviews/JinLin-Electric-Co-Reviews-E763647.htm",
"Seasons In Malibu@@www.seasonsmalibu.com@http://www.glassdoor.com/Salary/Seasons-In-Malibu-Salaries-E771400.htm",
"Kawasaki Heavy Industries@@www.khi.co.jp@http://www.glassdoor.com/Reviews/Kawasaki-Heavy-Industries-Reviews-E6403.htm",
"Taiwan Power@@www.taipower.com.tw@http://www.glassdoor.com/Reviews/Taiwan-Power-Reviews-E8274.htm",
"Jama@@www.jama.com.tw@http://www.glassdoor.com/Reviews/Jama-Reviews-E149693.htm",
"Tainan University of Technology@@www.tut.edu.tw@http://www.glassdoor.com/Salary/Tainan-University-of-Technology-Salaries-E255381.htm",
"Shin Kong Life Insurance Co@@www.skl.com.tw@http://www.glassdoor.com/Salary/Shin-Kong-Life-Insurance-Co-Salaries-E256363.htm",
"Cowell@@www.cowell.com.tw@http://www.glassdoor.com/Salary/Cowell-Salaries-E305175.htm",
"Lunghwa University of Science and Technology@@www.lhu.edu.tw@http://www.glassdoor.com/Salary/Lunghwa-University-of-Science-and-Technology-Salaries-E323762.htm",
"Birmingham Investment Management@@www.bimg.com.tw@http://www.glassdoor.com/Reviews/Birmingham-Investment-Management-Reviews-E349906.htm",
"Kylink Communications Corp.@@www.kylink.com.tw@http://www.glassdoor.com/Reviews/Kylink-Communications-Corp-Reviews-E351582.htm",
"DEM@@www.dem-global.com@http://www.glassdoor.com/Salary/DEM-Salaries-E351796.htm",
"Atoptech@@www.atoptech.com@http://www.glassdoor.com/Salary/Atoptech-Salaries-E360364.htm",
"Topco Scientific@@www.topco-global.com@http://www.glassdoor.com/Reviews/Topco-Scientific-Reviews-E363061.htm",
"IWICS, Inc.@@www.iwics.com@http://www.glassdoor.com/Reviews/IWICS-Inc-Reviews-E364223.htm",
"Leo Systems@@www.leosys.com@http://www.glassdoor.com/Reviews/Leo-Systems-Reviews-E370709.htm",
"GID@@www.gid.com.tw@http://www.glassdoor.com/Salary/GID-Salaries-E373056.htm",
"Synology@@www.synology.com@http://www.glassdoor.com/Salary/Synology-Salaries-E413038.htm",
"The Institute of International Relations@@www.iir.nccu.edu.tw@http://www.glassdoor.com/Reviews/The-Institute-of-International-Relations-Reviews-E442498.htm",
"Medialand@@www.medialand.com.tw@http://www.glassdoor.com/Salary/Medialand-Salaries-E468307.htm",
"HannsTouch Solution@@www.sintek.com.tw@http://www.glassdoor.com/Reviews/HannsTouch-Solution-Reviews-E556490.htm",
"Tesa Tape@@www.tesatape.com@http://www.glassdoor.com/Salary/Tesa-Tape-Salaries-E569876.htm",
"Canbran International@@www.hairhelp.can.com.tw@http://www.glassdoor.com/Reviews/Canbran-International-Reviews-E582223.htm",
"Crown Machinery@@crowntex.com@http://www.glassdoor.com/Reviews/Crown-Machinery-Reviews-E590219.htm",
"Rexchip Electronics@@www.rexchip.com@http://www.glassdoor.com/Reviews/Rexchip-Electronics-Reviews-E599883.htm",
"TrendForce@@www.trendforce.com@http://www.glassdoor.com/Reviews/TrendForce-Reviews-E614300.htm",
"Bio-Architecture Formosana@@www.bioarch.com.tw@http://www.glassdoor.com/Reviews/Bio-Architecture-Formosana-Reviews-E614765.htm",
"China Medical University Hospital@@www.cmuh.cmu.edu.tw@http://www.glassdoor.com/Salary/China-Medical-University-Hospital-Salaries-E620188.htm",
"Symphox Information@@www.symphox.net@http://www.glassdoor.com/Reviews/Symphox-Information-Reviews-E620203.htm",
"Lextar Electronics@@www.lextar.com@http://www.glassdoor.com/Salary/Lextar-Electronics-Salaries-E629209.htm",
"Intelligent Manpower@@www.jobnet.com.tw@http://www.glassdoor.com/Salary/Intelligent-Manpower-Salaries-E639354.htm",
"Maioli ETRC@@etrc.mlc.edu.tw@http://www.glassdoor.com/Reviews/Maioli-ETRC-Reviews-E647137.htm",
"Whole Globe Enterprise@@wholeglobe-chemtech.com@http://www.glassdoor.com/Reviews/Whole-Globe-Enterprise-Reviews-E652343.htm",
"Business Today@@www.businesstoday.com.tw@http://www.glassdoor.com/Reviews/Business-Today-Reviews-E653707.htm",
"CSBC@@www.csbcnet.com@http://www.glassdoor.com/Salary/CSBC-Salaries-E659374.htm",
"AGENDA@@www.agenda-asia.com@http://www.glassdoor.com/Salary/AGENDA-Salaries-E665223.htm",
"Chang Jung Christian University@@www.cjcu.edu.tw@http://www.glassdoor.com/Reviews/Chang-Jung-Christian-University-Reviews-E669739.htm",
"Mitake@@www.mitake.com.tw@http://www.glassdoor.com/Salary/Mitake-Salaries-E670737.htm",
"Camelot Technology Corporation@@www.camelottw.com@http://www.glassdoor.com/Reviews/Camelot-Technology-Corporation-Reviews-E674904.htm",
"Hiwin@@www.hiwin.com@http://www.glassdoor.com/Reviews/Hiwin-Reviews-E684391.htm",
"Tachan Securities@@www.tachan.com.tw@http://www.glassdoor.com/Reviews/Tachan-Securities-Reviews-E692099.htm",
"National Hsinchu University of Education@@www.nhcue.edu.tw@http://www.glassdoor.com/Reviews/National-Hsinchu-University-of-Education-Reviews-E695936.htm",
"Acumen Co.@@www.acumen.com.tw@http://www.glassdoor.com/Reviews/Acumen-Co-Reviews-E730325.htm",
"Chang YI Investment@@www.cch.org.tw@http://www.glassdoor.com/Salary/Chang-YI-Investment-Salaries-E743679.htm",
"Changhua Christian Hospital@@www.grandex.com.tw@http://www.glassdoor.com/Salary/Changhua-Christian-Hospital-Salaries-E747508.htm",
"Grandex@@www.cptt.com.tw@http://www.glassdoor.com/Reviews/Grandex-Reviews-E771905.htm",
"Chunghwa Picture Tubes@@www.msi.com.tw@http://www.glassdoor.com/Reviews/Chunghwa-Picture-Tubes-Reviews-E25691.htm",
"Micro-Star International@@www.walsin.com.tw@http://www.glassdoor.com/Salary/Micro-Star-International-Salaries-E41141.htm",
"Walsin Lihwa@@www.cathayholdings.com.tw@http://www.glassdoor.com/Salary/Walsin-Lihwa-Salaries-E41148.htm",
"Cathay Financial Holding@@www.wneweb.com@http://www.glassdoor.com/Salary/Cathay-Financial-Holding-Salaries-E41977.htm",
"Wistron NeWeb@@www.nchc.org.tw@http://www.glassdoor.com/Salary/Wistron-NeWeb-Salaries-E42573.htm",
"National Center for High-performance Computing@@www.mega.com@http://www.glassdoor.com/Salary/National-Center-for-High-performance-Computing-Salaries-E214723.htm",
"Manz Automation@@www.manz-automation.com@http://www.glassdoor.com/Reviews/Manz-Automation-Reviews-E229729.htm",
"Brainchild@@www.brainchild.com@http://www.glassdoor.com/Salary/Brainchild-Salaries-E264982.htm",
"System Integrity Engineering@@www.sieinc.com@http://www.glassdoor.com/Salary/System-Integrity-Engineering-Salaries-E279474.htm",
"TAITRA@@www.taitra.org.tw@http://www.glassdoor.com/Salary/TAITRA-Salaries-E397830.htm",
"1111 Job Bank@@www.1111.com.tw@http://www.glassdoor.com/Salary/1111-Job-Bank-Salaries-E418875.htm",
"Splashtop@@www.splashtop.com@http://www.glassdoor.com/Salary/Splashtop-Salaries-E420054.htm",
"Back Garden Cafe@@www.backgarden.com.tw@http://www.glassdoor.com/Salary/Back-Garden-Cafe-Salaries-E454740.htm",
"Morrison Academy@@www.mca.org.tw@http://www.glassdoor.com/Reviews/Morrison-Academy-Reviews-E474878.htm",
"Mega Securities@@www.emega.com.tw@http://www.glassdoor.com/Reviews/Mega-Securities-Reviews-E476170.htm",
"Taipei City Goverment@@www.taipei.gov.tw@http://www.glassdoor.com/Salary/Taipei-City-Goverment-Salaries-E477531.htm",
"National Palace Museum@@www.npm.gov.tw@http://www.glassdoor.com/Reviews/National-Palace-Museum-Reviews-E499004.htm",
"beBit@@www.bebit.co.jp@http://www.glassdoor.com/Salary/beBit-Salaries-E525329.htm",
"Chung Shing Group@@www.csgroup-bus.com.tw@http://www.glassdoor.com/Reviews/Chung-Shing-Group-Reviews-E557078.htm",
"Visgeneer@@www.visgeneer.com.tw@http://www.glassdoor.com/Reviews/Visgeneer-Reviews-E583957.htm",
"Artkey@@www.artkey.com@http://www.glassdoor.com/Reviews/Artkey-Reviews-E595262.htm",
"Canon Marketing (Taiwan)@@www.canon.com.tw@http://www.glassdoor.com/Reviews/Canon-Marketing-Taiwan-Reviews-E612171.htm",
"Taiwan International Ports Corporation@@www.twport.com.tw@http://www.glassdoor.com/Reviews/Taiwan-International-Ports-Corporation-Reviews-E612977.htm",
"National Taiwan University of Science and Technology@@www-e.ntust.edu.tw@http://www.glassdoor.com/Salary/National-Taiwan-University-of-Science-and-Technology-Salaries-E615722.htm",
"Zinwell@@www.zinwell.com.tw@http://www.glassdoor.com/Reviews/Zinwell-Reviews-E627064.htm",
"Intumit@@www.intumit.com@http://www.glassdoor.com/Reviews/Intumit-Reviews-E654762.htm"
];
